### ISSUE TITLE
something is broken in the System constructor here

### ISSUE THREAD

**Issue by aeilers** [fnalabs/hive-js#32]
All other tests pass for each browser.

Safari error:
```
Safari 11.1.0 (Mac OS X 10.13.4) class System "before each" hook for "should create an Actor System" FAILED
        function is not a constructor (evaluating 'super()')
        System@/tmp/src/System/BaseSystem.js:63:4 <- /tmp/d6ac2b825d4d5a60831fd0d710053c78.browserify:33283:10
	/tmp/tst/System.spec.js:49:17 <- /tmp/d6ac2b825d4d5a60831fd0d710053c78.browserify:34143:38
	asyncFunctionResume@[native code]
	[native code]
	promiseReactionJob@[native code]
```

Chrome Mobile error:
```
Chrome Mobile 63.0.3239 (Android 8.0.0) class System "before each" hook for "should create an Actor System" FAILED
        TypeError: Illegal constructor
            at new System (/tmp/src/System/BaseSystem.js:63:4 <- /tmp/d6ac2b825d4d5a60831fd0d710053c78.browserify:33283:5)
            at Context._Actor.Actor (/tmp/tst/System.spec.js:49:17 <- /tmp/d6ac2b825d4d5a60831fd0d710053c78.browserify:34143:18)
	    at <anonymous>
```

**Comment by aeilers** [comment]
Fixed in #36.
